- database/mongodb.js
- database/postgres.js
- database/redis.js
- models/test.js
- router/test.js
- server.js
- manages connections in `@database/*` 
- manages mongoose schemas in `@models`
> Feature: establish PostgreSQL, MongoDB, Redis database connection

- utility/validation.js
- 두 번째 키 값을 targetString에서 message로
- 두 번째 value 값을 변경
> Style: rewrite throwing JSON message

- router/test.js
- server.js
- handler reads key {statusCode}, {message}, {messages} of the error
- object prints stacktrace on server side error
> Feat: enable custom exception handler and its test apis

- .vscode/settings.json
- router/user.js
- server.js
- 가입 시 기존 유저 존재 여부 체크
- 첫 로그인일 경우 RDB에 정보 추가
- 로그아웃은 `/user/signout`에 포함해야 하여 미구현
> 카카오 OAuth 가입, 로그인, 탈퇴 구현

- router/user.js
- utility/session.js
- `import { [function] } '@utility/session'` to use
> 리팩터링: 세션 관리를 위한 Utility 분리

- router/user.js
- utility/kakao.js
use `import * as kakao from '@utility/kakao'` to use
> 리팩터링: 카카오 OAuth REST API 호출 코드 분리

- router/user.js
> Fix: set cookie path to root

- router/test.js
- router/user.js
- utility/session.js
* `await redisClient.get(`session:${userId}`)`를 통해 사용자 `userId`의 세션 ID 확인
* 비로그인 상태시 `null`
> 사용자 ID를 통한 로그인 여부 확인 기능 추가 및 세션 관련 코드 점검

- router/user.js
> 사용자 DB 테이블 병합 사항 반영

- router/user.js
- utility/sms-auth.js
* `GET /user/auth-code?receiverNumber=[tel]` to send
* `POST /user/auth-code/check` to check (body contains key `authCode`)
> SMS 인증, 검증 API 추가

- router/user.js
`/user/auth-code/check`의 body에 `phoneNumber` 값 필요
> Fix: check phone number to check auth code

- jsconfig.json
Babel로 설정한 Path Alias 설정을 IntelliSense에 반영하기 위해 경로 설정 추가
> jsconfig.json 추가

- router/notice.js
- router/report.js
- router/user.js
서브 쿼리를 이용하여 `lastPage` 반환
lastPage는 SELECT 결과의 수를 10으로 나눈 것의 소수 첫째자리에서 올림한 결과
> 마지막 페이지 번호를 반환하도록 notice, report, user 라우터 수정

- middleware/user.js
- router/user.js
`GET /user/username/availability`
> Feat: create username availability check api

- middleware/page.js
- router/notice.js
- router/report.js
- router/user.js
- utility/validation.js
* 공백 여부 검증을 위해 `Number()` 대신 `parseInt()` 사용
> 숫자 범위 validation 추가 및 페이지 번호 예외처리 수정

- .babelrc
- game/core.js
- jsconfig.json
- package-lock.json
- package.json
- server.js
- socket/kkujjang.js
게임 개발 시 `server.js` 내 웹소켓 코드는 수정 불필요
게임 개발 시에는 `@game/*`, `@socket/kkujjang` 수정
> 웹소켓 및 게임 베이스 생성

- router/test.js
/middleware 의 콜백함수를 async로 변경
정규표현식 검증 라우터 추가
> Feat: test regExp in /test

- middleware/user.js
- router/test.js
- router/user.js
주요 로직
```
WITH 
my_serial AS (
SELECT nextval('kkujjang.user_id_seq'::regclass) AS id
)
INSERT INTO kkujjang.user (id, username, password, phone, nickname)
SELECT 
my_serial.id, 
$1, 
crypt($2, gen_salt('bf')), 
$3, 
'${defaultNickname}' || '#' || CAST(my_serial.id AS VARCHAR)
FROM my_serial 
```
기존에는 id에 값을 주지 않았을 때 DEFAULT로 호출되는 ```nextval('kkujjang.user_id_seq'::regclass)```를 
직접 호출하여 ```serial```을 만들고 이를 통해 ```id```와 ```nickname```을 결정해줍니다
> Refactor: /user

- middleware/user.js
- router/user.js
- utility/kakao.js
* 카카오 로그아웃 추가
* 회원 탈퇴 API 통일
* 로그인할 때 redirect URL을 받도록 수정
> 카카오 로그아웃, 회원 탈퇴 기능 추가, 로그인 코드 개선

- package-lock.json
- package.json
- router/ranking.js
- server.js
- utility/ranking.js
npm 모듈이 추가되었습니다
```
"node-schedule": "2.1.1"
```
랭킹 매기는 기준입니다(쿼리문 참고)
1. 레벨순
2. 경험치순
정렬 기준입니다(쿼리문 참고)
1. 레벨순
2. 경험치순
3. id(계정 생성)순
```
SELECT 
CAST(RANK() OVER (ORDER BY level DESC, exp DESC) AS INT) AS rank, 
id, 
level, 
nickname 
FROM kkujjang.user
ORDER BY level DESC, exp DESC, id ASC
LIMIT 100
```
> Feat: ranking

- package.json
- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-api-server/src/router/test.js
- packages/kkujjang-game-server/index.js
- packages/kkujjang-game-server/src/game/gameRoom.js
- packages/kkujjang-game-server/src/game/lobby.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/kkujjang-game-server/src/utility/error.js
- 게임방에서 다른 게임방 접속 불가
- 게임방번호 추가
- 4000번 포트로 쿠키와 http request를 보낼 수 있게 cors옵션 추가
- package.json의 script 수정
- 환경변수 추가
```
WS_PORT
WSS_PORT
```
> Feat: socket exception handler AND cors options

- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-game-server/src/game/game.js
- packages/kkujjang-game-server/src/game/gameRoom.js
- packages/kkujjang-game-server/src/game/lobby.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/kkujjang-session/src/auth.js
* 현재 차례인 유저가 게임 중 퇴장 시 해당 라운드 종료, 아니라면 해당 유저 제외하고 정상 진행
* 게임 종료 후 방이 대기 상태로 변경되도록 수정
* API 서버 세션 부재시 게임 접속 불가
* 타 기기 혹은 여러 브라우저에서 동시 접속 불가
> Feat: handle exceptions of user signed in already and exitting during the game 

- .dockerignore
- Dockerfile.api
- Dockerfile.game
- data/mongodb/init.js
- data/postgres/init.sql
- docker-compose.dev.yaml
- docker-compose.prod.yaml
- package.json
- packages/postgres/index.js
`.env` must be like:
```env
HTTP_PORT=
HTTPS_PORT=
WS_PORT=
WSS_PORT=
PGPORT=
POSTGRES_HOST=
POSTGRES_NAME=
POSTGRES_TEST_NAME=
POSTGRES_USER=
POSTGRES_PASSWORD=
MONGODB_PORT=
MONGODB_HOST=
MONGODB_NAME=
MONGODB_TEST_NAME=
MONGODB_USER=
MONGODB_PASSWORD=
MONGO_INITDB_ROOT_USERNAME=
MONGO_INITDB_ROOT_PASSWORD=
REDIS_PORT=
REDIS_HOST=
REDIS_PASSWORD=
REDIS_DB=
REDIS_TEST_DB=
KAKAO_REDIRECT_URI=
KAKAO_REST_API_KEY=
SEMDM_REST_API_KEY=
SENDM_ID=
SEMDM_CALLER_NUMBER=
SESSION_EXPIRES_IN=
ADMIN_AUTHORITY=
STDICT_KOREAN_API_KEY=
```
> Chore: configure docker compose

- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-game-server/src/game/game.js
- packages/kkujjang-game-server/src/game/gameRoom.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
* 게임 타이머 정보를 턴 시작이 아닌 게임 시작 시 초기화하도록 변경
> Feat: add timeout to game procedure

- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-game-server/src/socket/kkujjang.js
두개의 server to client emit 메시지 추가
```
load new room
```
방이 만들어지면 방 정보를 클라이언트에 보낸다
```
destory room
```
방이 지워지면 그 방의 id를 클라이언트에 보내서 화면에서 지우게 한다
> Feat: emit load game and destory room  to client

- packages/kkujjang-api-server/index.js
- packages/kkujjang-game-server/index.js
개발 서버일 경우에만 CORS 설정에서 모든 Origin을 허용
> Feat: allow all origins when dev

- package-lock.json
- package.json
- packages/kkujjang-api-server/index.js
- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-api-server/src/middleware/room.js
- packages/kkujjang-api-server/src/router/chat.js
- packages/kkujjang-api-server/src/router/room.js
- packages/kkujjang-game-server/index.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/logger/index.js
- packages/logger/src/roomLogger.js
- packages/mongo-pool/index.js
- packages/mongo-pool/model/room.js
response형태는 API명세서 참고해주세요(03-12에 변경)
오류 수정
- join room애서 userId말고 room status를 매개변수로 전달하는 오류 수정
- complete join room에서 매개변수를 전달하는 오류 수정
> Feat: room and game logger

- packages/kkujjang-api-server/src/router/notice.js
left join으로 table 값이 존재하지 않을 때도 join 되도록함
이 때 files의 value는 null이됨
> Fix: when file is not exist

- packages/kkujjang-api-server/public/socket_test.html
- packages/kkujjang-game-server/src/game/lobby.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/kkujjang-game-server/src/utility/error.js
**수정사항**
1. ```chat``` userId 포함해서 보내기 
2. ```switch ready state``` index 정보 바꾸기
3. ```change room owner``` 로직 오류
> Fix: errors in socket

- packages/kkujjang-game-server/src/game/game.js
- packages/kkujjang-game-server/src/game/gameRoom.js
- packages/kkujjang-game-server/src/game/lobby.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/kkujjang-game-server/src/utility/error.js
1. reset ready state
2. 한글자 채팅처리
3. 방 떠나도 이미게임방입니다 버그 수정
4. API 통신 실패시 핸들링
5. 기타 message를 글로벌 변수로
> Fix: socket errors

- packages/kkujjang-api-server/src/router/ban.js
- packages/kkujjang-api-server/src/router/test.js
- packages/rabbitmq/index.js
- packages/rabbitmq/package.json
> Feat: redis Flushall in test router

- packages/kkujjang-api-server/src/middleware/chat.js
- packages/kkujjang-api-server/src/router/chat.js
- packages/kkujjang-api-server/src/router/notice.js
- packages/kkujjang-api-server/src/router/report.js
- packages/kkujjang-api-server/src/router/room.js
- packages/kkujjang-game-server/src/socket/kkujjang.js
- packages/logger/src/chatLogger.js
- packages/mongo-pool/model/chat.js
오류 및 일부 style 수정
채팅로그
-방id도 insert
-방id로 검색 가능
신고
-oldest가 내림차순으로 작동하던 코드 수정
-쿼리 return 순서가 통일되게 style 수정
-대소문자 구별되게 쿼리문 수정
공지
-content대신 id를 return하게 쿼리문 수정
> Fix: api and logger

- .gitignore
- docker-compose.dev.yaml
- docker-compose.prod.yaml
- package.json
- `.env.prod` and `.env.dev` required for production, dev build each.
- `cert` directory required in project root directory
- `SSL_KEY_LOCATION`, `SSL_CRT_LOCATION`, `SSL_CA_LOCATION` env var required for production build to use ssl
> modify docker compose for ssl
